# Generated by Django 4.2.1 on 2023-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='title',
            field=models.TextField(default='title text'),
        ),
    ]
