# Generated by Django 4.2.1 on 2023-05-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0006_question_score_ratings_score_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='score',
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
